### ISSUE TITLE
tS Word Edition: Support Published Content

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/QuarterlyObjectives#20]
We need to have Word formatted documents that allow for people to translate and then upload back into our system for:

* [x] OBS
* [x] ~~OBS tN~~
* [x] ~~OBS tW~~
* [x] ~~OBS tQ~~
* [x] ~~tA~~

Issue is at https://github.com/unfoldingWord-dev/Door43/issues/317

**Comment by jag3773** [comment]
Relevant Door43 issue: https://github.com/unfoldingWord-dev/Door43/issues/317

**Comment by leok22** [comment]
Blocked for lack of people resources. Waiting on #6
