### ISSUE TITLE
Finish Build GL Team

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/QuarterlyObjectives#29]
The rest of the GL team needs to be found and on boarded.

Found:
* [x] South Asia
* [x] Eurasia
* [x] Asia
* [x] Africa
* [x] Americas
* [x] Pacific

Onboarded:
* [x] South Asia
* [x] Eurasia
* [x] Asia
* [x] Africa
* [x] Americas
* [x] Pacific

**Comment by Picofeo** [comment]
My first time modifying settings in here - sorry.  The GLD Americas position has been filled, so all the team are in place, but Kwesi - the GLD Africa guy still has a few weeks before he's been in a MAST and had all of his financial/reporting/plans in place.  He should be fully on-boarded by mid December.  How do that show that in here on this particular task?  Almost done.

**Comment by Picofeo** [comment]
Other than some refresher training that some of the guys will receive in several software programs that they use in their jobs with WA, everybody I currently have is on-boarded.  I am still the Americas GLD, and can continue this way for another few months.
